update

diff --git a/.github/workflows/ios-build.yml b/.github/workflows/ios-build.yml
--- a/.github/workflows/ios-build.yml
+++ b/.github/workflows/ios-build.yml
@@ -16,6 +16,8 @@ jobs:
       KEYCHAIN_PASSWORD: actions-keychain-pass
       TEAM_ID: 72M97MR8UU
       BUNDLE_IDENTIFIER: com.example.farra
+      CODE_SIGN_IDENTITY="iPhone Distribution: Farok Omar (72M97MR8UU)"
+
 
       # Base64 P12 تقسیم‌شده برای دور زدن محدودیت محیطی
       P12_PART1: MIIM+AIBAzCCDKYGCSqGSIb3DQEHAaCCDJcEggyTMIIMjzCCBsoGCSqGSIb3DQEHBqCCBrswgga3AgEAMIIGsAYJKoZIhvcNAQcBMF8GCSqGSIb3DQEFDTBSMDEGCSqGSIb3DQEFDDAkBBDOmNpScT+q6Z28jL8cBOK6AgIIADAMBggqhkiG9w0CCQUAMB0GCWCGSAFlAwQBKgQQbpXtbbzJCW4txuBuP7lre4CCBkCDmjUaLCfl4Ze29zLfX56yuFsvFLr1cVj7gh7A9NJCTF05zx8crnyPbxjcAo5C4CRQsTxc9cGy9U3n1R6qQEDVN+aXvvv7W6YL9Etrx+Wx7bo37U80BQan6B1Rff4H8OLV4f1xCkknPVF++nXA7gjsjuXgz+WGHbyLs6aGb2FGRlxq0oKqhUKxzs3G/xPTd099LKxWoWZIDX+B59CnHon/+7+3zkee1rxIECPve+eBCOUaZgmUoNUPQA8nscYlWNIV5L769oWy7akLkq1FMiB7L+T//nFQclR9+IDqqHN3pjh4pIMLOR66XaOWhVHuNMxyqYsAdVpS/KT+T2BjSca9WuWgKdoG3m1fH0e+8RT50WEf3zAfybQnXx4favfLfnIjotPKYT788wGFbM4IpdiruYwja2+Z4HoKlvXUhxb/x4UhPEDyIERCxv19IjDfu1WkIw9LfbDLkQ0JzuQPLslxky2vjAeFX8gOvLGs6yAw71MsczjQpv044K+paX0PPFtfjtZo+XeXoO9eGNAxoC9euBalwS0W0PqF/cmWKSEgADupPqncuf1gEmTPndMPub52jKcI9J8iiL8L4rWDJpux58D4t66PQid3ToMYfN8LcAV/WgtHRx5tgBRpuveQDZRfUYw+ttLf84FBsN3sg4yrmJguUYy+E6H9Iq6Uz0GxRBpVVQyUBoUYOEvJwpBu5g0SqrqRmZc2D/iiMLbwKLZJlULagZnVmoxsyS3iZIBbICVzw/1wcSDRWWEMniLTlZdCFmDdPmbhKAO2OdTwJERJWoV6D6NkXk/+4Bev6jUvd4R5aKNH0MBKl4PAshk9cwiqeaQaMNOVTGXJOc88XRa0hyYKZwNmcXqa5dlwOqaDUSWtkhYy6oWBhqvKGSSjcIABLZzOopLLAK3sDsAlcBnc0ZIAOlkLI9ytDpUsjLB4yDlkeltZksZ/AhcNpxnaN7doT0MfSCfn9hkRVcrfk+u7rSVjXBzq8ZEd0xHiT9MJmoJzmnpBn3/NNeHDvxzdbfwOYRzwuP+cj1iFbVMHPbxDWnaZn7ekU6YIDsyjIIIAD/GjKtd08mcNJZ92OOEiT/+r+DVLfiVAT2VPcR6ZXOURtGNU90PJJSArlaFgmVPzZZ3gQ8cWvveH53X0h0Z2x6fWmY9/rAtnbyzRwZe/ARf5TijI9Ohu7nQi5acQeGdmMHIq+DsWpVxKv0HfMl1C0J95JUa9hdHLAyr6IJKIX0TiD+A86ivbSVgsdZGvLxaYGCIjtgS/uqK6hd99Fyf6+89vwNdbZ1J+XLgQ+BKywn9uLnNz9HD4p0llMdryVmfqn2HW5nGpvMFvCRoXikKwmjWcI27QviubsQ47qcwgbDm2K5hFeqXdJM6sOD9Mr4lr6OPp0IFkgvC4hOA9FhEAknzNeIEgGAFXZ7ai2WlU+CighKsSjgV2BDL8UVG26tMs4mu00vUcH+5uA9vCtCKmS9VYZRnoszRF5PovqBvB0RP+uF4BNjv7IVBRhYVFR/hOF8jRPfE+2i6FdzT54WW8V2h93PbCG/oI52FBXfRJZsNeL9VFJwrleltfY3FgaOClFlDfX8BOy9NmKKhfYLDTC+bEkzwwOv3nTSWEI92T+CXEzv6mYf2VtsSZ6PLNPAxgBJof0UnvY9J7VMifntyh4Up21fxgYQf2jbN0Qe5ggml0cfvg19B3XuIi/EiwUgGqWo7Usi9VuJu9JAu2e8LhFxLJ8ocBlKe9fa8KcbJOIGmAp+rU5QT2xw1Q6OfWc9QXhu2/a0MvPUFZlLmDK77ngipm2Sle7tgWSx9I3tTc82TwL7fiNicNBhcrAUlyjeN8xYmMrZzHPHOtsMCZ3Dtu/edsuEey+AP/wkzBNBdB6pt0EUTT258ZRZCU1jAYaC7UkDtUn4Di4o27HBM52Db0OUlWEnMCxLwmXTJih4baTuoWTeTjM6GCc8bNhjNj05Z+Sj0fil+rWV/ovTUxzgK23KDkVWs5jMoGrb5wxnyDs66Zgffts/uEXGk6zPhl/6TyqZmd0Iy6gXizslnWIfExMVyS0iHt2OcLhER
@@ -44,7 +46,7 @@ jobs:
           echo "Starting P12 reconstruction and decode using 3 parts..."
 
           FULL_P12_B64="${P12_PART1}${P12_PART2}${P12_PART3}"
-          echo "$FULL_P12_B64" | tr -d '\n' | base64 --decode > "${P12_FILE_NAME}" \
+          printf "%s" "$FULL_P12_B64" | base64 --decode > "${P12_FILE_NAME}" \
             || { echo "❌ Failed to decode P12."; exit 1; }
 
           echo "${{ env.PROVISIONING_PROFILE }}" | tr -d '\n' | base64 --decode > "${PP_FILE_NAME}" \
@@ -69,26 +71,27 @@ jobs:
           security set-keychain-settings -lut 14400 ~/Library/Keychains/login.keychain
 
           echo "💬 Creating password file safely..."
-           cat <<'EOF' > p12pass.txt
-               $KEYCHAIN_PASSWORD
-                EOF
+          printf "%s" "$KEYCHAIN_PASSWORD" > p12pass.txt
+          dos2unix p12pass.txt
+
           cat p12pass.txt | wc -c | xargs echo "🔑 Password length:"
 
           echo "📥 Import certificate"
           security import "${P12_FILE_NAME}" \
-            -k ~/Library/Keychains/login.keychain \
-            -P "$(cat p12pass.txt)" \
-            -A -t cert -f pkcs12 \
-            -T /usr/bin/codesign \
-            -T /usr/bin/security || {
-            echo "::error::❌ Failed during P12 import"; exit 1; }
+          -k ~/Library/Keychains/login.keychain-db \
+          -P "$(cat p12pass.txt)" \
+          -T /usr/bin/codesign \
+          -T /usr/bin/security \
+          || { echo "::error::❌ Failed during P12 import"; exit 1; }
+ 
 
           echo "🔓 Allow codesign access"
           security set-key-partition-list \
-            -S apple-tool:,apple:,codesign: \
-            -k "$KEYCHAIN_PASSWORD" \
-            -D "Apple Distribution" \
-            ~/Library/Keychains/login.keychain
+          -S apple-tool:,apple:,codesign: \
+          -k "$KEYCHAIN_PASSWORD" \
+          -D "${CODE_SIGN_IDENTITY}" \
+          ~/Library/Keychains/login.keychain-db
+
 
           echo "📲 Install provisioning profile"
           PP_UUID=$(/usr/libexec/PlistBuddy -c "Print UUID" /dev/stdin <<< "$(security cms -D -i "${PP_FILE_NAME}")")
@@ -127,7 +130,7 @@ jobs:
          # Generate clean build.xcconfig
          cat > "$IOS_XCCONFIG" <<EOF
          CODE_SIGN_STYLE = Manual
-         CODE_SIGN_IDENTITY = Apple Distribution
+         CODE_SIGN_IDENTITY = iPhone Distribution: Farok Omar (72M97MR8UU)
          PROVISIONING_PROFILE_SPECIFIER = ${PP_UUID}
          DEVELOPMENT_TEAM = ${TEAM_ID}
          PRODUCT_BUNDLE_IDENTIFIER = ${BUNDLE_IDENTIFIER}
@@ -171,4 +174,5 @@ jobs:
           echo "🧹 Cleaning up temporary files..."
           rm -f "${P12_FILE_NAME}" 2>/dev/null || true
           rm -f temp_p12_b64.txt 2>/dev/null || true
+          rm -f p12pass.txt 2>/dev/null || true
           echo "✅ Cleanup completed (non-blocking)"
